export const PERMISSIONS = {
    // Général
    USER: 'USER',

    // Dashboard
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',

    // Recours
    VIEW_CLAIMS: 'VIEW_CLAIMS',
    CREATE_CLAIM: 'CREATE_CLAIM',
    UPDATE_CLAIM: 'UPDATE_CLAIM',
    VALIDATE_CLAIM: 'VALIDATE_CLAIM',
    REJECT_CLAIM: 'REJECT_CLAIM',

    VIEW_CLAIM_DOCUMENTS: 'VIEW_CLAIM_DOCUMENTS',
    UPLOAD_CLAIM_DOCUMENT: 'UPLOAD_CLAIM_DOCUMENT',
    DELETE_CLAIM_DOCUMENT: 'DELETE_CLAIM_DOCUMENT',
    VIEW_CLAIM_MESSAGES: 'VIEW_CLAIM_MESSAGES',
    SEND_CLAIM_MESSAGE: 'SEND_CLAIM_MESSAGE',

    // États (statements)
    VIEW_STATEMENTS: 'VIEW_STATEMENTS',
    EXPORT_STATEMENTS_PDF: 'EXPORT_STATEMENTS_PDF',
    ARCHIVE_STATEMENTS: 'ARCHIVE_STATEMENTS',

    // Compagnies
    VIEW_COMPANIES: 'VIEW_COMPANIES',
    CREATE_COMPANY: 'CREATE_COMPANY',
    UPDATE_COMPANY: 'UPDATE_COMPANY',
    UPDATE_COMPANY_LOGO: 'UPDATE_COMPANY_LOGO',

    // Notifications
    VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',

    // Profil / compte
    VIEW_PROFILE: 'VIEW_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',

    // Admin (users & roles)
    MANAGE_USERS: 'MANAGE_USERS',
    MANAGE_ROLES: 'MANAGE_ROLES',
};
